### ISSUE TITLE
Recurring issues with applying simple templates

### ISSUE THREAD

**Issue by aexshafii** [different-ai/file-organizer-2000#101]
I'm struggling to have simple instructions successfully applied to my templates. Example: 

https://www.loom.com/share/3ff5facc77a048dbb72902b679aac353

I think we should adjust the instructions to our server for higher success rates

**Comment by ashgansh** [comment]
is this talking to prod?

**Comment by aexshafii** [comment]
Self deployed. Latest version. Prod front end.

**Comment by ashgansh** [comment]
can you share template and text?

**Comment by ashgansh** [comment]
fixed
