### ISSUE TITLE
Often moves to my "Daily Notes" folder. 

### ISSUE THREAD

**Issue by bhanna** [different-ai/file-organizer-2000#107]
The plugin often moves a file to seemingly random folders in my "Daily Notes" folder. I never want it to put things in my daily notes folder. 

Should have option to exclude folder from auto organize.

My folder is set up as follows:

<img width="264" alt="image" src="https://github.com/different-ai/file-organizer-2000/assets/490148/44c4bac7-ed97-4c0f-b39f-06529a190799">

**Comment by ashgansh** [comment]
hey there @bhanna !

makes sense i just pushed a change that will allow you to force ignore folders in the settings.

**will be released in the store on wednesday** (along with a huge amount of changes!)

if you can't wait and are a bit technical you can try to clone the repo and run it today already

**Comment by ashgansh** [comment]
@bhanna this is now added :)
