### ISSUE TITLE
Anthropic model setup producing error

### ISSUE THREAD

**Issue by lyonisaac** [different-ai/file-organizer-2000#108]
I've enabled Anthropic model usage and have it configured to use the latest Haiku model throughout. I've generated a fresh API key which I've set up, and have tried restarting Obsidian to allow changes to propagate. I'm getting what seems to be a generalized error for the tool. Can confirm that I'm able to successfully use OpenAI models without errors. 

![Screenshot of image configuration](https://github.com/different-ai/file-organizer-2000/assets/148653908/11f165d1-6575-4d90-8e8d-87259fe71a29)

![Screenshot of error on assistant sidebar](https://github.com/different-ai/file-organizer-2000/assets/148653908/e3bb30f6-d056-41b8-934e-7a1690fe6c59)

**Comment by ashgansh** [comment]
@lyonisaac will look into it thanks for reporting

our most tested models are:
1. gpt-4o
2. codegemma (open source)
3. groq (llama-70b)


i will test with haiku today
