### ISSUE TITLE
Always picks up custom URL regardless of options - bug

### ISSUE THREAD

**Issue by benwalio** [different-ai/file-organizer-2000#114]
**Description**
When specifying pro key or w/e, if you set the customurl to the localhost default then turn it back off, it'll still try to connect to localhost.

**proposed fix**
Guessing that there's something that's ignoring the the custom server enabled boolean in the settings

**workaround**
Enable the Custom Server in the settings and replace with `https://app.fileorganizer2000.com` then disable, everything works fine then

**symptoms**
loads of these errors in the console
```
plugin:fileorganizer2000:58010 Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)

plugin:fileorganizer2000:57945 Uncaught (in promise) Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
```

**other considerations**
OS - mac m1
I had previously rolled out my own server for funsies, and it was working. then opted for subscribing and changed over to a pro account key

**settings jsons**
working
```
{
{...},
"defaultServerUrl": "https://app.fileorganizer2000.com", 
"customServerUrl": "https://app.fileorganizer2000.com", 
"usePro": true, 
"useCustomServer": false, 
{...}
}
```
busted
```
{...},
"defaultServerUrl": "https://app.fileorganizer2000.com", 
"customServerUrl": "http://localhost:3000", 
"usePro": true, 
"useCustomServer": false,
{...}
```

**Comment by benwalio** [comment]
I can take a looksee later in the weekend and see about slapping together a PR, but someone more familiar with the codebase might be able to knock this out in 30 seconds since it appears to be a missing flag check. (famous last words)

**Comment by ashgansh** [comment]
hi @benwalio thanks for reporting this, i think i can get it fixed in a few min with your explanations ;)

i'll ping you when new version is live

**Comment by ashgansh** [comment]
tested a bit looks like this should cover it:
https://github.com/different-ai/file-organizer-2000/commit/f64217ef0b58b2216485c56ce241cfa32463260d


you can update the plugin to latest (^1.5.14)

(didn't have too much time to test so keep me posted if it still doesn't behave as expected)

**Comment by benwalio** [comment]
tested and it looked good! thank you!
