### ISSUE TITLE
Audio Transcription Error

### ISSUE THREAD

**Issue by bhanna** [different-ai/file-organizer-2000#127]
<img width="328" alt="image" src="https://github.com/different-ai/file-organizer-2000/assets/490148/c8a12c11-d424-4fb2-aadf-8967eaa4bf0d">

Audio files put in Inbox do not transcribe, and result in an error. 

Files are renamed: 
- Document summary needed.m4a
- Document summary needed.md 

And randomly put in a folder.

All other functions seem to be working just fine.

**Comment by aexshafii** [comment]
@bhanna Thanks for reporting. Working on a fix.

**Comment by aexshafii** [comment]
hey @bhanna So we have decided to scrap the feature for now, as it didn't meet our quality standards. We will revisit in the future if we see a demand for it. Is this an important one for you? By the way the app is up and running again if you are a PRO user

**Comment by bhanna** [comment]
Oh no! That was a great feature, and was super useful. I could dictate voice memos to my watch on the go and just drop them in the inbox for it to sort them when I got to my computer.

In the meantime I have been using an app called Bebop that saves a file to any folder i want and just using dictation to the keyboard on my phone. It saves it in the inbox folder so that it automatically gets processed.

I can probably write a python script or apple automation with a folder watcher to do the voice memo transcription on my own with whisper and then drop the transcribed file in the organizer inbox.

I combined this with the "tasks" plug-in for a supercharged to do list workflow.

I am not on the pro plan, as I am using my own API for open AI, and using vercel.

Here is my task list template:
-----

If the item seems to be a task list or task list dictation, parse it, and pull out any definitive "tasks." For each of these tasks, format them exactly like the following:

- [ ] TASK HERE #TAG 📅 YYYY-MM-DD
Shoot
Where TASK HERE is the task, #TAG is a list of tags formatted as #tag1 #tag2 etc.  The date emoji signifies the due date in YYYY-MM-DD format. It should always default to tomorrow.

If any links or URLs are including in the text, include them EXACTLY and do not edit them.

---

 - Ben Hanna
________________________________

**Comment by aexshafii** [comment]
@bhanna Ahhh I see. thanks for sharing your use case. This is exactly the type of workflow we envisioned people to create so great to hear that you had this working well for you. Sorry that we had to take the feature out for now. Will let you know if/when we plan on re-implementing it.

 How do you manage to get your memos sent to the inbox via your watch exactly? Is it an Apple Watch?

**Comment by bhanna** [comment]
Yes, Apple Watch with iCloud sync on for Voice Memo's. Any voice memo's made on apple watch automatically sync to iphone. Then I use the "Add to Obsidian" shortcut to drop them in the FO2k inbox.

**Comment by aexshafii** [comment]
Ahhh nice. Got it. Thanks for sharing. Will close the issue now and let you know when we bring the feature back 🙏

**Comment by ashgansh** [comment]
@bhanna we added this feature back. availabile since 1.6.5
