### ISSUE TITLE
When you don't have any tags in the vault the auto tag generation misbehaves

### ISSUE THREAD

**Issue by ashgansh** [different-ai/file-organizer-2000#13]
See image below: 

![image](https://github.com/different-ai/file-organizer-2000/assets/11430621/03ab7b3e-82bb-4739-bf9c-899d107f4496)

using tag generation in a vault without tags just creates bullet points instead of #

**Comment by aexshafii** [comment]
on it

**Comment by aexshafii** [comment]
fixed and tested. Seems to behave as expected 100% of the time

**Comment by ashgansh** [comment]
#15
