### ISSUE TITLE
Template formatting just says [object Object]

### ISSUE THREAD

**Issue by objectiveSee** [different-ai/file-organizer-2000#133]
I am using this plugin to apply templates to existing documents. I have a template like this:

```
Make a bullet point list from the contents of this file. Use emojis for bullet points
```

Which I am trying to apply to a note that looks like this:

```
THIS IS A TASK LIST:

Open Door
Close Door
```

When I apply the template, the document contents gets replaced with:
```
[object Object]
```

Step 1:
![Screenshot 2024-06-17 at 12 01 10 PM](https://github.com/different-ai/file-organizer-2000/assets/1684106/0b4b7410-23b4-4539-b0ec-562d1287cc8f)

Step 2:
![Screenshot 2024-06-17 at 12 01 31 PM](https://github.com/different-ai/file-organizer-2000/assets/1684106/f9615d3f-af24-4813-9c02-dabaddb24852)

**Comment by aexshafii** [comment]
hey @objectiveSee thanks for reporting. Just pushed  a fix. Can you update the plugin and try again?

**Comment by objectiveSee** [comment]
Thanks for the quick fix @aexshafii! It seems to be working with the latest update 🙏
