### ISSUE TITLE
[rename] use existing title + document content 

### ISSUE THREAD

**Issue by louis030195** [different-ai/file-organizer-2000#139]
if im not wrong rename does not use existing doc title?

https://github.com/different-ai/file-organizer-2000/blob/f0236f496a3d456e731bb25025b32f7aa15d45df/app/aiService.ts#L133

usually my workflow:

1. cmd+n new note (notes are named using timestamp like 063034 12345)
2. brain dump an idea
3. add title at the end

with fo2k currently it just rename my file like "law vs integrity" from "063034 12345 law vs integrity" (i pref the later to keep track of the date)

my prompt:

<img width="825" alt="image" src="https://github.com/different-ai/file-organizer-2000/assets/25003283/7c9474fd-0510-4933-a6bb-e938a6f96a4d">

(jsut realised title is not used)

i'd like either:
1. use existing doc title in the prompt 
2. be able to disable document rename when moving to inbox 
3. something else

**Comment by ashgansh** [comment]
thanks for notifying us

it was a bug, it is now included (we also added the current date as a context)
