### ISSUE TITLE
What are possible values for local llm with ollama.

### ISSUE THREAD

**Issue by Malli88** [different-ai/file-organizer-2000#145]
Hi, and first thank you for the superb plugin. It's just awesome!
Could you give please a little bit more documentation about the local llm configuration?
Specific, I mean what possible values there are for adding in the field LLM Model?
I use llama3:70B and couldn't get it up and running.
And, what does you mean with the hint to the Ollama Orgins?

Thanks a lot!

**Comment by muhammadammarzahid** [comment]
Can you please guide me how to use local installation of ollama? From my understanding, I used the following environment

```
environment # Uncomment lines below for a fully local setup
 MODEL_FOLDERS=llama3
 MODEL_RELATIONSHIPS=llama3
 MODEL_TAGGING=llama3
 MODEL_NAME=llama3
 MODEL_TEXT=llama3
 MODEL_VISION=llava-llama3


### The fastest way to get started is just to add your OpenAI API key to the .env file.
#OPENAI_API_KEY="sk"
```
But requests always look for an OPENAI_API_KEY. Do I need to fire up the ollama server myself and make any changes in the configuration?

**Comment by YoavTamir00** [comment]
I also enountered this problem
