### ISSUE TITLE
AI Templates overwrite existing information instead of just adding new information

### ISSUE THREAD

**Issue by Malli88** [different-ai/file-organizer-2000#147]
If you have maybe a template to create a summary, the application of that template will create a summary but will also delete all data from the file.

**Comment by aexshafii** [comment]
@Malli88 Sorry about that. We released a feature since that adds a link to a backup of any note you format with templates. Hope this will solve your issues!

**Comment by Malli88** [comment]
Nothing to apologize here. You do a great job.
I could make it work by writing better prompt.
