### ISSUE TITLE
AI Suggestions for images

### ISSUE THREAD

**Issue by Cossackx** [different-ai/file-organizer-2000#150]
I know this can be done if I move the image into the /inbox folder but it would be great if I don't have to move images from their locations in the vault. Can the same functionality in the /inbox be done with the FO2K Assistant in the sidebar?
![image](https://github.com/user-attachments/assets/8f6e1d14-2c26-432b-a95c-38ff3aa2174d)

**Comment by aexshafii** [comment]
@Cossackx Yes it can be done but it would be quite costly in regards to AI tokens. 

We actually had this functionality before but removed it as it wasn't sustainable in its previous implementation at least.
