### ISSUE TITLE
iOS shortcut setup and how it works

### ISSUE THREAD

**Issue by louis030195** [different-ai/file-organizer-2000#2]
I assume the ios shortcut need obsidian on your phone + some sync like obsidian sync?

I stopped using Obsidian on my iphone because my vault is too big, unusable 

Just using apple notes on my phone for brain dumps that I sync to obsidian later (until i find better workflow)

I think if my apple notes could move automatically to obsidian somehow + processed by the plugin would be amazing (or other workflow)

**Comment by ashgansh** [comment]
>I think if my apple notes could move automatically to obsidian somehow + processed by the plugin would be amazing (or other workflow)

Hmmm that's a great idea actually, i'll see what apis are available.

**Comment by ashgansh** [comment]
> I assume the ios shortcut need obsidian on your phone + some sync like obsidian sync?
the shortcut expects filesystem access to how you sync Obsidian. I tested it with google drive and i cloud. i don't know how obsidian sync works.

**Comment by Cossackx** [comment]
I'm still not figuring it out. Can you walk me through? Also, how to you so easily get it to append at the end of the daily note?

**Comment by ashgansh** [comment]
@aexshafii could you test if the shortcut works ? 

https://www.icloud.com/shortcuts/06915768862848fb9711f2f19b6405e2 

we should make it easier to be used
