### ISSUE TITLE
Issues with Excalidraw - Can't Open Excalidraw Property Menu if Fo2k is Enabled

### ISSUE THREAD

**Issue by cybersader** [different-ai/file-organizer-2000#219]
When I turned on File Organizer for my vault, I could not open the property panel in Excalidraw.  I'm not sure why or how.  My vault -> (https://github.com/cybersader/awesome-cybersader/tree/main)

**Comment by aexshafii** [comment]
@cybersader there must be a conflict somewhere. will look into it

**Comment by RONNYKHALIL** [comment]
+1, thank u

**Comment by aexshafii** [comment]
@cybersader @RONNYKHALIL fixed in v1.47.3 

<img width="605" alt="Screenshot 2024-09-26 at 9 54 11 AM" src="https://github.com/user-attachments/assets/b5b65e37-7cde-4622-812e-785bc731e404">

**Comment by cybersader** [comment]
Thank you!

**Comment by RONNYKHALIL** [comment]
yip yip! and fabric support, to boot! nice :)
