### ISSUE TITLE
Feature request: Confirmation prior to file organization

### ISSUE THREAD

**Issue by devinat1** [different-ai/file-organizer-2000#22]
I would like and option to toggle wherein I "confirm" either note by note or small batches of notes which are moved. This is because the LLM could hallucinate or otherwise select a title/tags/folder incorrectly, and I would like more granular control over what is happening.

**Comment by ashgansh** [comment]
working on some prototypes for this should be shipped this week

**Comment by ashgansh** [comment]
wdyt of going in this direction?

https://www.youtube.com/watch?v=9o-4MhIifMk

**Comment by devinat1** [comment]
That is great, thank you! I had one tangentially related request: Could aliases be recommended? That is, synonyms to a link name get added to the aliases.

**Comment by ashgansh** [comment]
i added something again in that direction, but reading your text now again i think could've misunderstood.

is that what you were asking for (demos a bit more towards en)
https://youtu.be/oaxLplzWOKs

**Comment by devinat1** [comment]
Yes you understand right thank you. I was also thinking if a note already has a title, then similar words to that title can be chosen. Example: title = happy, then all similar titles to happy, such as happiness, happier, happiest are added to the alias.
But I think your implementation also takes into account the entirety of the document which is even better.
But my point is: There are two scenarios
- Title already made and the tags/aliases/content can be part of that
- Nothing made, and file organizer 2000 is used to "take the wheel" and organize everything for you.

A way to select what "stage your note in" in your processing could be useful.
One way to implement this could be to have a "system prompt" similar to ChatGPTs GPTs in which the intent of how the user wants their notes to look like can be given as a prompt which alters the decision process of the LLM as to which file names/links/tags to give.
Example related to my post https://github.com/different-ai/file-organizer-2000/issues/21 is the system prompt:
"Organize all notes in a Zettelkasten fashion Use #MOC for maps of content and #idea for zettels, and name accordingly..."
I'm not sure how feasible is, but that is my suggestion and I thank you for this addon!

**Comment by ashgansh** [comment]
@devinat1 you're reading my mind, that's exactly where we want to go with this plugin

<img width="969" alt="Screenshot 2024-04-17 at 23 15 38" src="https://github.com/different-ai/file-organizer-2000/assets/11430621/c96537a0-39ec-408f-9bcd-608d5c32c2e0">


link to full article here: https://publish.obsidian.md/on-the-fence/Essays/AI+in+Obsidian+-+Automating+the+boring+parts

will just iterate our way there !


we'll try to ship something soon :)

**Comment by ashgansh** [comment]
> "Organize all notes in a Zettelkasten fashion Use #MOC for maps of content and #idea for zettels, and name accordingly..."

great feedback btw


I will try to tackle a simplified version of this like this:
https://github.com/different-ai/file-organizer-2000/issues/40#issue-2249295749

**Comment by devinat1** [comment]
Sweet, looking forward to it!
