### ISSUE TITLE
Unable to self host

### ISSUE THREAD

**Issue by dianedef** [different-ai/file-organizer-2000#231]
I'm trying to self host o Windows with my limited abilities.
Please help me resolve this error : 

npm error A complete log of this run can be found in: C:\Users\Shadow\AppData\Local\npm-cache\_logs\2024-09-08T15_02_30_638Z-debug-0.log
PS C:\Users\Shadow> cd file-organizer-2000
PS C:\Users\Shadow\file-organizer-2000> npm run build:self-host; npm run start
npm error Missing script: "build:self-host"
npm error
npm error To see a list of scripts, run:
npm error   npm run

npm error A complete log of this run can be found in: C:\Users\Shadow\AppData\Local\npm-cache\_logs\2024-09-08T15_02_46_137Z-debug-0.log
npm error Missing script: "start"
npm error
npm error Did you mean one of these?
npm error   npm star # Mark your favorite packages
npm error   npm stars # View packages marked as favorites
npm error
npm error To see a list of scripts, run:
npm error   npm run

npm error A complete log of this run can be found in: C:\Users\Shadow\AppData\Local\npm-cache\_logs\2024-09-08T15_02_46_604Z-debug-0.log

**Comment by aexshafii** [comment]
@dianedef You first need to access the web folder with the command: `cd web` and then run the other commands

**Comment by dianedef** [comment]
Thank you. I still get the same errors.

Now this is what I get:

C:\Users\Shadow\file-organizer-2000\web>npm run build:self-host

> file-organizer-app@0.1.0 build:self-host
> next build

'next' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.


or...




C:\Users\Shadow\file-organizer-2000\web>npm run build:self-host; npm run start
npm error Missing script: "build:self-host;"
npm error
npm error Did you mean this?
npm error   npm run build:self-host # run the "build:self-host" package script
npm error
npm error To see a list of scripts, run:
npm error   npm run

npm error A complete log of this run can be found in: C:\Users\Shadow\AppData\Local\npm-cache\_logs\2024-09-11T11_34_11_516Z-debug-0.log

**Comment by fawazy3077** [comment]
when i try self house i have this error
PS C:\Users\vddsff> cd web
cd : Cannot find path 'C:\Users\fasto\web' because it does not exist.
At line:1 char:1
+ cd web
+ ~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\vddsff\web:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by Johannnnes** [comment]
> when i try self house i have this error PS C:\Users\vddsff> cd web cd : Cannot find path 

try this:
cd ./packages/web

**Comment by aexshafii** [comment]
@fawazy3077 yes there were some changes recently. @Johannnnes thanks that is indeed the new command. 
I will update the docs today
