### ISSUE TITLE
feedback on UI 

### ISSUE THREAD

**Issue by louis030195** [different-ai/file-organizer-2000#24]
i keep forgetting to move to folder, maybe an alternative UI could be a suggestion notification somewhere for files in root folder for example to suggest to move and add tags?

also specific use case to me probably is that 95% of my notes are public (published) and private notes are in the "Louis" folder so i want to avoid at all cost that some private notes end up outside this folder, for example a conversation with a friend with transcription etc.

**Comment by ashgansh** [comment]
1. will try something today, and will ask you for feedback once it's shipped
2. will work on something also in the direction, in the end we think the power of this is to make it hyper customizable

**Comment by louis030195** [comment]
or maybe it could be a kind of reminder notifcation to move ro foler until its in my workflow

**Comment by ashgansh** [comment]
wdyt of this direction? solving your problem #1 ?
https://www.youtube.com/watch?v=9o-4MhIifMk

**Comment by aexshafii** [comment]
<img width="515" alt="Screenshot 2024-04-18 at 8 58 01 AM" src="https://github.com/different-ai/file-organizer-2000/assets/46509400/1e6ff7b5-6f10-445f-aad0-cf1499330057">

Just found it actually. But I would rename it to 'Move current file to Inbox folder' so it could be found more easily.
