### ISSUE TITLE
Changing AI model?

### ISSUE THREAD

**Issue by Mailmanek** [different-ai/file-organizer-2000#240]
Hey, 
I am burning through my openAI API money. How can I change the model used to GPT 4o mini?

I am not a dummy when it comes to computers but I am NOT a developer. So... go slow on me. 

I am on the lifetime plan of FO2k btw.

**Comment by aexshafii** [comment]
hey @Mailmanek Ahh yeah gpt-4o can be quite expensive. Made this video this morning showing you how to easily configure gpt-4o-mini: https://youtu.be/yVZn-cGOMzE

let me know if that works
🙏

**Comment by Mailmanek** [comment]
Hey, so great of you to immediately respond!

I think the change to gpt4o-mini worked. I am testing it right now.
However, I can have a general chat or a chat about one file within the chat
window but I cannot talk to the files in a whole folder (wasn't
it @foldername at the beginning of the request?) or files with a certain
hashtag. When I try something with @foldername or anything, I get:
"All notes modified within the following time period were added to the AI
context: {"startDate":"2024-09-10","endDate":"2024-09-18"}"

It simply adds all the files in between those dates (from the entire
vault). So, here is what I think happened (roughly). I've just started
keeping a journal in one folder and right now there are notes whose names
simply are the dates they were created. From 2024-09-10 to 2024-09-18. I
wanted the AI to find patterns in those entries and theirs was the folder
that I tried to add to the context with @foldername. So... did the AI
somehow read the names of those files (dates) and misunderstood it in that
way that it was supposed to add ALL files created between those dates?
If yes, then this could be a problem that other people may have as well. I
don't think it is uncommon to have Notes with just a date as the name. Not
just for journals.

You know what, even though even gpt4o-mini burns quite a bit of money and I
don't think I will use it much, keep those 99€ to keep up the good work.
This is going in a great direction.

**Comment by aexshafii** [comment]
@Mailmanek I see. The app is optimized and developed around gpt-4o. So there might be some discrepancies when configuring other models. We have found in general that results were also noticeably inferior with gpt-4o-mini, and pretty much any other models we tried. We initially put a lot of effort into making it compatible with a wide range of models, but that proved to be super time-intensive so we decided to focus on the best model we could put our hands on. 

The models will keep getting cheaper, and further down the line, our goal is to have a 100% local LLM-only model that would be free. In the meantime, you could also try any openAI compatible provider, such as groq, which could be considerably cheaper than gpt-4o-mini.

In any case. Thanks so much for your support. Really appreciate it 🙏
