### ISSUE TITLE
feat: add instructions for custom folder moving logic

### ISSUE THREAD

**Issue by aexshafii** [different-ai/file-organizer-2000#241]
## Background

File Organizer 2000 is an AI-powered plugin for Obsidian that helps users keep their vault organized. When a user moves a note to the File Organizer Inbox Folder, it's automatically moved to the most appropriate folder in the user's vault based on an AI request.

## Current Functionality

- Folder determination is handled by a non-customizable prompt in the `ai-service` file, specifically the `guessRelevantFolder` function.
- The plugin sends all folder names in the user's Obsidian app to this endpoint: `web/app/api/(newai)/folders/route.ts`.

## Proposed Feature

Allow users to add custom instructions for better folder determination:

1. **New Setting**: Add a new setting in the plugin's experimental features list for custom folder moving logic.
2. **User Instructions**: Enable users to write a few lines of instructions, similar to the existing renaming instructions in the plugin settings.

## Implementation Notes

- **UI Update**: Update the plugin settings UI to include the new custom instructions field.
- **AI Request Modification**: Modify the AI request to incorporate these custom instructions when determining the appropriate folder.
- **Toggle Feature**: Ensure the feature is toggleable in the customization tab of the plugin settings.

## Additional Information

- I will provide you with an openAI key to run the server
- Instructions on how to self-host can be found on our github readme

## Setup Instructions for Developers

1. **Install Obsidian**: Ensure Obsidian is installed if not already available.
2. **Install Plugin**: Clone the project into your vault (see loom video).
3. **Plugin Settings**: In the plugin settings, navigate to the customization tab.
4. **Toggle Settings**: Disable all toggles except the first two in customization section of settings, : renaming + logs to minimize openAI costs.

## Additional Developer Notes

- **API Key**: I will provide an API key necessary for accessing the AI-powered features.
- **Dev Mode**: Instructions on how to run the plugin in development mode within Obsidian will be provided to facilitate testing and debugging.

Ensure thorough testing of this new feature to maintain the plugin's reliability and user experience.

You'll need to clone the project inside a vault you created (Dev in this example). In the "plugins" folder as seen below
<img width="955" alt="Screenshot 2024-09-21 at 2 17 19 PM 2" src="https://github.com/user-attachments/assets/8c0f0ed5-fe0f-4f73-906e-7d15e32b9cfa">

Reach out for any questions

Here's a loom video with a quick walkthrough: https://www.loom.com/share/c9b4cb3decf14662bba0393d20953576

**Comment by akhilender-bongirwar** [comment]
@aexshafii, I am interested in working on this issue. My local setup is up and running. Could you provide me with the `OpenAI API key` and instructions for obtaining the `File Organizer license key`?

**Comment by aexshafii** [comment]
@akhilender-bongirwar Awesome! Email me at alex@fileorganizer2000.com and I'll send that over to you. 🙏
