### ISSUE TITLE
Fix get youtube transcript error

### ISSUE THREAD

**Issue by aexshafii** [different-ai/file-organizer-2000#245]
File Organizer 2000 is an Obsidian plugin that includes an AI Chat, similar to chatGPT. One of the functionalities it has is that it can retrieve YouTube transcripts. And users can extract information about it. It works quite well. However, at times it mentions that it could could not retrieve the transcript. Although it actually does. We don't want this type of message to appear: 

_I currently don't have access to the transcript for the YouTube video with the ID "SwQhKFMxmDY". If you have any other requests or need assistance with something else, feel free to let me know!_

It should only appear when it was actually really not retrieved.

There are two solutions that are acceptable. Either: 
- don't show that message
- show a message mentioning it was successfully retrieved

but should still appear when it was not retrieved

<img width="747" alt="Screenshot 2024-10-01 at 11 08 35 AM" src="https://github.com/user-attachments/assets/3b38e27c-abd2-4971-88eb-020ceb128b1d">

<img width="747" alt="Screenshot 2024-10-01 at 11 08 35 AM" src="https://github.com/user-attachments/assets/1dcf7c61-3f43-4907-988f-75a89365cce1">

**Additional Information**

I will provide you with an openAI key to run the server
Instructions on how to self-host can be found on our github readme

**Setup Instructions for Developers**

Install Obsidian: Ensure Obsidian is installed if not already available.
Install Plugin: Clone the project into your vault (see loom video).

**Additional Developer Notes**

Ensure thorough testing of this new feature to maintain the plugin's reliability and user experience.

You'll need to clone the project inside a vault you created (Dev in this example). In the "plugins" folder as seen below
![image](https://github.com/user-attachments/assets/71099053-fe0f-4e8b-8e5d-ab792b7452a3)

Where to clone the repo: 
https://www.loom.com/share/c9b4cb3decf14662bba0393d20953576

Reach out for any questions

**Comment by neo773** [comment]
I keep getting this `Failed to load plugin "fileorganizer2000"`. Tried installing `node_modules` and running dev command.

<img width="367" alt="image" src="https://github.com/user-attachments/assets/59731029-5843-4931-aab2-f91e53c7e02c">

**Comment by aexshafii** [comment]
@neo773 @iamhvsharma is any of you still tackling this issue?

**Comment by iamhvsharma** [comment]
Yes I am working on it!!! 
Understanding the codebase as of now!
