### ISSUE TITLE
Charged by mistake

### ISSUE THREAD

**Issue by marconisoares** [different-ai/file-organizer-2000#248]
Hey here. I was looking for an e-mail to send this request, but I couldn't find any on the webpage.
I have tried to cancel my subscription because, during the trial, I realize it doesn't suit me as needed. 

As I didn't find a button to go back to the free subscription, I had deleted my account so, I expect, I wouldn't be charged.

Unfortunately I was. How should I proceed?

Thanks a lot!

**Comment by aexshafii** [comment]
@marconisoares sure just reach out with your email address via alex@fileorganizer2000.com so I know which account to process the refund to.
🙏
