### ISSUE TITLE
fix: folder Suggestions Mismatch

### ISSUE THREAD

**Issue by aexshafii** [different-ai/file-organizer-2000#249]
## Description

In FileOrganizer 2000, there's an issue with the folder suggestions functionality in the Assistant sidebar. Sometimes, the suggested folders do not correspond to the currently open file, but instead show suggestions for a different file.

see video with detailed info: https://www.loom.com/share/0df511bf88ff4f8a8b3820b9dfac270e
## Steps to Reproduce
1. Open FileOrganizer 2000
2. Click on the Assistant sidebar button
3. Navigate between different files (e.g., "Expenses 2024", "Napoleon", "Hummingbird", "Porsche Boxster")
4. Observe the folder suggestions for each file

## Expected Behavior
The folder suggestions should always match the active file.

## Actual Behavior
Occasionally, the folder suggestions are for a different file than the one currently open. For example:
- When viewing a file about Napoleon, suggestions for birdwatching appear
- When viewing a file about a Hummingbird, suggestions for French History appear

## Additional Information
- The issue seems to occur randomly
- It's possible that suggestions from different files are being mixed together
- The problem affects both existing folder suggestions and new folder suggestions

## Possible Fix
Ensure that the folder suggestion functions are always using the context of the currently active file when making API requests or processing results.

## Attachments
[Hummingbird.md](https://github.com/user-attachments/files/17265652/Hummingbird.md)
[Napoleon.md](https://github.com/user-attachments/files/17265653/Napoleon.md)
[Porsche Boxster.md](https://github.com/user-attachments/files/17265654/Porsche.Boxster.md)

## Additional Notes
- Creating 9-10 test folders (e.g., cars, history, animals) with distinct themes may help in testing and reproducing the issue more consistently.
- The issue persists regardless of whether the embedding method or standard method is used for suggestions.

**Comment by dguerabes** [comment]
Hello !
I have seen API calls with bad values. With the title of the current page but the content of the previous page.
I have a fix to not make those calls.

**Comment by aexshafii** [comment]
@dguerabes approved ✅ thanks a lot. will also see if I can reproduce the issues with titles that you mention.
