### ISSUE TITLE
fabric file path

### ISSUE THREAD

**Issue by RONNYKHALIL** [different-ai/file-organizer-2000#254]
Minor issue, but can you add fabric path to file config options? I have named my root file-organizer-2000 "_fo2k" and updated all folders in the config options to match. but with fabric enabled, it keeps creating a new folder "_FileOrganizer2000/Fabric". I found the line in main.js and changed it from 

    plugin.settings.fabricPatternPath = "_FileOrganizer2000/Fabric";
to
    plugin.settings.fabricPatternPath = "_fo2k";

but of course every time i update it would revert. having fabric path in file config would be helpful to prevent this

thanks!

**Comment by benjaminshafii** [comment]
hi @RONNYKHALIL sorry completely missed this. will add this this week.

**Comment by benjaminshafii** [comment]
@RONNYKHALIL sorry for delay, we shipped this today.
