### ISSUE TITLE
which app root folder for self host?

### ISSUE THREAD

**Issue by jhmonroe** [different-ai/file-organizer-2000#260]
Hello! 

Setting up self-hosting and am unclear which *app* you're referring to in your instructions below?

Do you mean inside Obsidian's root folder? Or your plugin's root? Or the root folder for my local web server? aka the localhost folder (In my case I'm testing a local web server using Flywheel Local which can run nginx or apache).

Would you consider simply making the API key slot a fill in the blank on the self-host tab that already has the checkbox and localhost URL location?

---
Self-hosting
Run the server
For Linux/macOS:
cd web && npm run build:self-host &&  npm run start
And make sure you have your OPENAI_API_KEY variable set up in your .env.local file inside the app root folder.
Go inside the Settings of the plugin and enable "Self-hosted"
---

I tried in every location I could think of and the plugin is not registering the API key and the chat doesn't respond with anything

Thank you!

**Comment by aexshafii** [comment]
hi @jhmonroe <img width="910" alt="Screenshot 2024-11-01 at 11 55 49 AM" src="https://github.com/user-attachments/assets/f19cfe0c-74c0-486b-8e7d-f270fc9df4ad">

It's in the root folder of the web folder as seen on the screenshot

**Comment by jhmonroe** [comment]
thank you! You're a saint :-) Excited to try out your plugin. Currently testing Logan's copilot and some others via API keys as well
