### ISSUE TITLE
Can it merge relevant note? 

### ISSUE THREAD

**Issue by darr1s** [different-ai/file-organizer-2000#266]
Hi, like title. 

I have a Notion exports it contains files of different structure, some file are from database which is lesser than 5 lines. 

The first time I run this, it moved all these files into their own folder and create 200+ folders. 

I want to know if this code supports lookup and merging file according to prompt/rules.

**Comment by benjaminshafii** [comment]
@darr1s not yet, but it's something we've been thinking about quite a bit.

**Comment by darr1s** [comment]
Good to know that, I'm new to AI/LLM.

Without involving bigger RAG tooling, and seems like there's some form of embedding already 

Is it possible to loop through the embedding + dir tree inb4 each next file according to written prompt rule?

**Comment by aexshafii** [comment]
hi @darr1s sorry for the late reply. Unfortunately it's not something that's possible at the moment
