### ISSUE TITLE
Bug Report: Issue with Tag Generation Format

### ISSUE THREAD

**Issue by 4rr0wx** [different-ai/file-organizer-2000#285]
Model: GPT-4o-mini
Version: 1.131.1

Problem Description:
Tags generated by the model are not formatted as nested tags (with a slash / as instructed) but instead use an underline _ between words. While the generated tags are correct in terms of content, the format does not align with the given instructions.

Example:

    Expected Format: IT/Docker
    Actual Output: IT_Docker

Instructions Provided to the Model:

>Generate tags that capture the main topics, themes, and type of content in the document. Focus on specific, meaningful tags that will >help with organization and retrieval.
>Create Nested Tags with the following format if there is a subtype: "MainTopic/SubTopic"
>Example: "theme/home"

Question:

    Is this an issue with the model's output logic (bug)?
    Or do I need to modify the instructions to ensure the correct tag format (e.g., nested tags with /)?

Expected Outcome:
Tags generated in the correct nested format, as per the instructions (e.g., MainTopic/SubTopic).

**Comment by benjaminshafii** [comment]
thx for reporting, we fixed this last week after you brought it to our attention 🙏
