### ISSUE TITLE
Feature Request: Add tags to YAML instead of body

### ISSUE THREAD

**Issue by Martin-Milbradt** [different-ai/file-organizer-2000#32]
Example:
```
---
note: AI Obsidian Manager
tags: obsidian, ai
alias:
  - AI Obsidian Manager
url: https://fileorganizer2000.com/
---
# [AI Obsidian Manager](https://fileorganizer2000.com/)
```

![image](https://github.com/different-ai/file-organizer-2000/assets/61841994/575ca81a-5062-48e3-b85f-252debde7e3d)

**Comment by ashgansh** [comment]
yeah @Martin-Milbradt was thinking about this just yesterday . will code this today.

will ping you when done!

**Comment by ashgansh** [comment]
https://www.youtube.com/watch?v=J-I5zYyDswk

will ship tomorrow

**Comment by ashgansh** [comment]
it's now live @Martin-Milbradt  :)

**Comment by ashgansh** [comment]
will test more this week, but yes this my go to setup right now. probably something to do with the empty list.

**Comment by aexshafii** [comment]
@Martin-Milbradt is this working as you'd expect now?

**Comment by Martin-Milbradt** [comment]
Still not adding any tags. And the logs are empty.

```
---
note: Warcraft III
tags: 
---
# Warcraft III

Warcraft III: Reforged is a remastered edition of the 2002 real-time strategy video game Warcraft III: Reign of Chaos and its expansion The Frozen Throne. Released on January 28, 2020, it adds revamped graphics, new campaign gameplay settings as well as modern online Battle.net features.

Very important: ADD the "game" tag to this!
```
![image](https://github.com/different-ai/file-organizer-2000/assets/61841994/5bf69a87-dae2-4543-b0af-cbab05dc5fdc)
