### ISSUE TITLE
Create a `.md` file that help onboard the users

### ISSUE THREAD

**Issue by ashgansh** [different-ai/file-organizer-2000#34]
Right now if you just installed fo2k, it's hard to now how you need to do it.

The endgame is that we show them a nice tutorial when they install file organizer + a button in settings where they can access it.

BUT, in the meantime. Let's just start by writing that document. as an .md file. 

For this task to be valid i need two things
- a screenshot of the md file inside of obsidian (so i can easily see how it looks like)
- a pr with that md file to the repo inside of `/tutorials`

**Comment by aexshafii** [comment]
<img width="792" alt="Screenshot 2024-04-17 at 12 15 16 PM" src="https://github.com/different-ai/file-organizer-2000/assets/46509400/8639ec61-9f2c-4243-8d61-402e1ffb9c32">

**Comment by aexshafii** [comment]
https://github.com/different-ai/file-organizer-2000/pull/39

**Comment by aexshafii** [comment]
<img width="792" alt="Screenshot 2024-04-17 at 12 45 06 PM" src="https://github.com/different-ai/file-organizer-2000/assets/46509400/ccd22a54-4fb4-44cf-94a0-68c106163643">

Revised Obisdian file

**Comment by ashgansh** [comment]
doesn’t really help the people use the app imo


i would focus on imagining they alorwdu have it installed


onboarding in this case means  using the app for the first time .
 

once you install the app and have your api key pasted we need to make sure the users  organizes the file at least once. that’s what the onoboqeding is supposed to achieve.

**Comment by aexshafii** [comment]
[
![Screenshot 2024-04-17 at 6 55 00 PM](https://github.com/different-ai/file-organizer-2000/assets/46509400/464ce1c2-ebbe-4ee4-be84-221399b2de9e)
](url)

Part 1 of 2

**Comment by aexshafii** [comment]
![Screenshot 2024-04-17 at 6 55 12 PM](https://github.com/different-ai/file-organizer-2000/assets/46509400/b15fd262-a3cc-4f9a-b45e-c8685c939556)

Part 2 of 2

**Comment by ashgansh** [comment]
looks good closing fo rnow
