### ISSUE TITLE
Make it possible to use OLLAMA for text use cases (only on self-host).

### ISSUE THREAD

**Issue by ashgansh** [different-ai/file-organizer-2000#35]
When the task is done people should be able to do this:
`USE_OLLAMA=true OPENAI_API_KEY=[sk-...] npm run start`

90% of this task should be on the server.

**We're only tackling text for now,** and we'll probably tackle audio transcription next.

**Comment by aexshafii** [comment]
We would not need an `OPENAI_API_KEY` in the case, would we?

**Comment by aexshafii** [comment]
on it

**Comment by aexshafii** [comment]
https://github.com/different-ai/file-organizer-2000/pull/50
