### ISSUE TITLE
Only send a request to /api/secret for early access with right amount of digits

### ISSUE THREAD

**Issue by ashgansh** [different-ai/file-organizer-2000#42]
if you type an early access code in settings you will get this error 

```
plugin:fileorganizer2000:307 Error activating Early Access Features: Error: Request failed, status 401
    at new t (app.js:1:[1977769](tel:1977769))
    at qG (app.js:1:[1977961](tel:1977961))
    at app.js:1:[1978638](tel:1978638)
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)
```

check for right amount of digit (let’s say 8)

so we wait until  chars before allowing to send the request to prevent  the request 

if we don’t do that we’re basically sending a request each time a user types a char and it triggers and error

**Comment by aexshafii** [comment]
https://github.com/different-ai/file-organizer-2000/pull/44
