### ISSUE TITLE
Bug: Tries to move file to nonexistant folder

### ISSUE THREAD

**Issue by Martin-Milbradt** [different-ai/file-organizer-2000#46]
![image](https://github.com/different-ai/file-organizer-2000/assets/61841994/f9e5ee65-6942-47b3-9e42-25b2f8b6247a)

I have a folder "Websites, Tools & Products", that might be the isse.

Note: It's also not logging anything to the logfiles or console, see #47.

**Comment by ashgansh** [comment]
damn that sucks 

we needed to downgrade to gpt3.5 today because costs were too high :(

we plan on giving access to best models to our supporters starting tomorrow.

**Comment by ashgansh** [comment]
i'll experiment a bit with these types of folders `Websites, Tools & Products` to make sure it's not something else than the model downgrade

**Comment by Martin-Milbradt** [comment]
Potentially relevant information: I use the self-hosted version.
