### ISSUE TITLE
Bug: Not logging errors

### ISSUE THREAD

**Issue by Martin-Milbradt** [different-ai/file-organizer-2000#47]
![image](https://github.com/different-ai/file-organizer-2000/assets/61841994/bcf76c7a-9848-4c36-ae08-6454155aea42)

All my logfiles (last 3 days) exist, but are empty. Changing the logdirectory had no effect. The error was only displayed once, the rest of the time nothing happens.

**Comment by ashgansh** [comment]
which os are you using?

**Comment by Martin-Milbradt** [comment]
Windows. There is a folder name in the path (before the `.obsidian`) in case that might be relevant.
