### ISSUE TITLE
429 openai

### ISSUE THREAD

**Issue by louis030195** [different-ai/file-organizer-2000#6]
reproduce:
1. move 5 files to inbox
2. 429

i suggest exponentialBackoff or something similar

```ts
function exponentialBackoff(retryFunction, maxAttempts, delay = 1000) {
  let attempts = 0;

  const attempt = () => {
    retryFunction().catch((error) => {
      if (error.status === 429 && attempts < maxAttempts) {
        attempts++;
        setTimeout(attempt, delay * Math.pow(2, attempts));
      } else {
        throw error;
      }
    });
  };

  attempt();
}
```

> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:17936 Error: 429
> useText @ plugin:fileorganizer2000:17936
> plugin:fileorganizer2000:18224 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
>     at FileOrganizer.getSimilarTags (plugin:fileorganizer2000:18224:28)
>     at async FileOrganizer.appendSimilarTags (plugin:fileorganizer2000:18268:25)
>     at async FileOrganizer.moveAndTagContent (plugin:fileorganizer2000:18093:5)
>     at async FileOrganizer.handleNonMediaFile (plugin:fileorganizer2000:18082:5)
>     at async FileOrganizer.processFileV2 (plugin:fileorganizer2000:18059:7)
> plugin:obsidian-git:44345 git obsidian message: Committed 4 files
> plugin:obsidian-git:43893 Pushing....
> plugin:obsidian-git:43895 Pushed! 4
> plugin:obsidian-git:44345 git obsidian message: Pushed 4 files to remote
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:17936 Error: 429
> useText @ plugin:fileorganizer2000:17936
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:17936 Error: 429
> useText @ plugin:fileorganizer2000:17936
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:17936 Error: 429
> useText @ plugin:fileorganizer2000:17936
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:17936 Error: 429
> useText @ plugin:fileorganizer2000:17936
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:17936 Error: 429
> useText @ plugin:fileorganizer2000:17936
> 2plugin:fileorganizer2000:14453 Uncaught (in promise) Error: Error:
>     at useName (plugin:fileorganizer2000:14453:11)
>     at async FileOrganizer.generateNameFromContent (plugin:fileorganizer2000:18157:18)
>     at async FileOrganizer.moveAndTagContent (plugin:fileorganizer2000:18085:35)
>     at async FileOrganizer.handleNonMediaFile (plugin:fileorganizer2000:18082:5)
>     at async FileOrganizer.processFileV2 (plugin:fileorganizer2000:18059:7)
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:14453 Uncaught (in promise) Error: Error:
>     at useName (plugin:fileorganizer2000:14453:11)
>     at async FileOrganizer.generateNameFromContent (plugin:fileorganizer2000:18157:18)
>     at async FileOrganizer.moveAndTagContent (plugin:fileorganizer2000:18085:35)
>     at async FileOrganizer.handleNonMediaFile (plugin:fileorganizer2000:18082:5)
>     at async FileOrganizer.processFileV2 (plugin:fileorganizer2000:18059:7)
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:17936 Error: 429
> useText @ plugin:fileorganizer2000:17936
> plugin:fileorganizer2000:18252 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
>     at FileOrganizer.getAIClassifiedFolder (plugin:fileorganizer2000:18252:51)
>     at async FileOrganizer.moveAndTagContent (plugin:fileorganizer2000:18088:31)
>     at async FileOrganizer.handleNonMediaFile (plugin:fileorganizer2000:18082:5)
>     at async FileOrganizer.processFileV2 (plugin:fileorganizer2000:18059:7)
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:17936 Error: 429
> useText @ plugin:fileorganizer2000:17936
> plugin:fileorganizer2000:18252 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
>     at FileOrganizer.getAIClassifiedFolder (plugin:fileorganizer2000:18252:51)
>     at async FileOrganizer.moveAndTagContent (plugin:fileorganizer2000:18088:31)
>     at async FileOrganizer.handleNonMediaFile (plugin:fileorganizer2000:18082:5)
>     at async FileOrganizer.processFileV2 (plugin:fileorganizer2000:18059:7)
> api.openai.com/v1/chat/completions:1     Failed to load resource: the server responded with a status of 429 ()
> plugin:fileorganizer2000:14453 Uncaught (in promise) Error: Error:
>     at useName (plugin:fileorganizer2000:14453:11)
>     at async FileOrganizer.generateNameFromContent (plugin:fileorganizer2000:18157:18)
>     at async FileOrganizer.moveAndTagContent (plugin:fileorganizer2000:18085:35)
>     at async FileOrganizer.handleNonMediaFile (plugin:fileorganizer2000:18082:5)
>     at async FileOrganizer.processFileV2 (plugin:fileorganizer2000:18059:7)

**Comment by devinat1** [comment]
This had happened to me with a different plugin (quickadd AI) since I had used up all my OpenAI API credits.

**Comment by ashgansh** [comment]
should be less of a problem atm, did you experience this again @louis030195 ?

**Comment by ashgansh** [comment]
fixed with using vercel sdk which has auto retry built in
