### ISSUE TITLE
Fix styling in settings

### ISSUE THREAD

**Issue by ashgansh** [different-ai/file-organizer-2000#68]
<img width="815" alt="Screenshot 2024-04-25 at 22 53 54" src="https://github.com/different-ai/file-organizer-2000/assets/11430621/b1e32337-9cdb-417d-9a89-b1b1978d8797">

**Comment by aexshafii** [comment]
<img width="606" alt="Screenshot 2024-04-26 at 3 03 06 PM" src="https://github.com/different-ai/file-organizer-2000/assets/46509400/fbe0971f-ee98-4e11-8f5d-569fb55fc694">

fixed: https://github.com/different-ai/file-organizer-2000/pull/69
