### ISSUE TITLE
Disable Sidebar when viewing a template

### ISSUE THREAD

**Issue by aexshafii** [different-ai/file-organizer-2000#73]
<img width="1032" alt="Screenshot 2024-04-26 at 8 31 19 PM" src="https://github.com/different-ai/file-organizer-2000/assets/46509400/4f1e33a3-8f23-4034-b9e5-f2c4b014662a">

**Comment by ashgansh** [comment]
do this task first maybe https://github.com/different-ai/file-organizer-2000/issues/76 so that you can find a good way to handle this you can do single pr
