### ISSUE TITLE
Bug: Missing publishableKey.

### ISSUE THREAD

**Issue by Martin-Milbradt** [different-ai/file-organizer-2000#77]
I'm getting the error on the self-hosted version. What could be wrong?
```
ENABLE_USER_MANAGEMENT False
   NEXT_PUBLIC_CLERK_IS_SATELLITE='true'`,n9="x-middleware-override-headers",n5="x-middleware-request",n8=(e,t,r)=>
   [...]
Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.
```

File Organizer API Key is set.
OPENAI_API_KEY set in environment variables and working.
Version: 1.4.4 (Server and plugin).
HTTP Status: 500

Note: I deleted `.eslintrc` since it caused issues and I think it's just linter settings.
It used to work a few versions ago.

Startup:
```powershell,
npm i
npm run build
$env:ENABLE_USER_MANAGEMENT=$false
npm run start
```

**Comment by aexshafii** [comment]
@Martin-Milbradt You need to have the following environment variable in your project: 

ENABLE_USER_MANAGEMENT=false

**Comment by ashgansh** [comment]
hi @Martin-Milbradt how are you running the api at the moment?

**Comment by ashgansh** [comment]
on my machine i run it like this:

```sh
npm run build
OPENAI_API_KEY=[some key] npm run start
```

**Comment by Martin-Milbradt** [comment]
I've set the OPENAI_API_KEY in the environment variables, and it used to work a few versions of file-organizer ago.

**Comment by Martin-Milbradt** [comment]
Still doesn't work after rebuild and specifying `ENABLE_USER_MANAGEMENT=$false`, but it's getting more complicated.

Output:
```
ENABLE_USER_MANAGEMENT False
   NEXT_PUBLIC_CLERK_IS_SATELLITE='true'`,n9="x-middleware-override-headers",n5="x-middleware-request",n8=(e,t,r)=>
   [...]
Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.
```

**Comment by ashgansh** [comment]
hmmm damn that sucks sorry about that

i just pushed a commit that i believe should fix it, could you pull and try again?

**Comment by Martin-Milbradt** [comment]
Looking good! There is an error message displayed, but the file is successfully moved.
Note: I'd expect the Tag `written` to get added, but fileorganizer doesn't catch that.
![image](https://github.com/different-ai/file-organizer-2000/assets/61841994/3b61f3b6-5bb9-4b6d-b378-63f5be0936d7)

**Comment by ashgansh** [comment]
hi @Martin-Milbradt we're getting significantly more issues since we downgraded to gpt-3.5-turbo :( with these types of things

there's also a few underlying problem (and we could do better error management and recover etc.) but simply upgrading to gpt-4-turbo solves 60% of issues on our side.

we will push a new update today to give  more control over this
