### ISSUE TITLE
Can't process images

### ISSUE THREAD

**Issue by aexshafii** [different-ai/file-organizer-2000#85]
https://www.loom.com/share/243c08d2274d42f48b9abe8c3428508c

**Comment by aexshafii** [comment]
![Screenshot 2024-05-07 at 11 56 19 AM](https://github.com/different-ai/file-organizer-2000/assets/46509400/109af5d0-ebfe-4b19-9274-29939f1ec4c3)
same on prod

**Comment by ashgansh** [comment]
fixed
