### ISSUE TITLE
Renaming Alias quirks

### ISSUE THREAD

**Issue by Kainkun** [different-ai/file-organizer-2000#88]
Thanks for the new "Rename untitled files only" feature 😁 But I noticed it still creates an alias which would always be redundant. Not sure if that's intended.
Also, I'm not sure if it makes sense for "Untitled" to become an alias when it gets renamed.

**Comment by ashgansh** [comment]
ah right that's not super smart.

there's an option to disable that in the settings.

we'll get to it soon.

btw are you using the self-hosted version?

**Comment by Kainkun** [comment]
Ah, cool.
I'm not self-hosted at the moment
