### ISSUE TITLE
When an image gets organized, we keep a wrong reference to the original file

### ISSUE THREAD

**Issue by ashgansh** [different-ai/file-organizer-2000#9]
This screenshot shows that the annotation log is not referencing the correct file anymore.

<img width="823" alt="Screenshot 2024-04-07 at 12 36 50" src="https://github.com/different-ai/file-organizer-2000/assets/11430621/a6b2baad-c6d3-4507-9442-17b0af7c166a">

**Comment by aexshafii** [comment]
on it

**Comment by aexshafii** [comment]
<img width="235" alt="Screenshot 2024-04-16 at 10 42 17 AM" src="https://github.com/different-ai/file-organizer-2000/assets/46509400/4fdd6d18-e279-4fc8-ad57-851e5e11bdff">

**Comment by aexshafii** [comment]
Addressed in this PR: https://github.com/different-ai/file-organizer-2000/pull/26

**Comment by aexshafii** [comment]
re-tackling this next today
