### ISSUE TITLE
Add prompt details so that AI Templates knows we are dealing with Markdown text

### ISSUE THREAD

**Issue by aexshafii** [different-ai/file-organizer-2000#97]

**Comment by aexshafii** [comment]
When I give instructions in my AI templates.It sometimes gets the formatting wrong. For example I asked to get it formatted into a table. And it was formatted into an HTML table, instead of Markdown.  It should format to optimize for Markdown/Obsidian.

**Comment by ashgansh** [comment]
attempted fix @aexshafii can you test again?
